### ISSUE TITLE
[enhancement] search string box dropdown with search history

### ISSUE THREAD

**Issue by SAbboushi** [bnason-nf/findallinfile#6]
Would like to be able to navigate through search history (up/down arrow) to fill the search string box; then I can either press Enter to do the same search or edit the string before pressing Enter to search

**Comment by bnason-nf** [comment]
Hi @SAbboushi,

This would be a nice feature. However, using the APIs provided by VSCode to extensions, I don't know if there's a nice way to do this, because I can't combine a text [input box](https://code.visualstudio.com/api/references/vscode-api#window.showInputBox) with a [quick pick](https://code.visualstudio.com/api/references/vscode-api#window.showQuickPick). I could show two dialogs if necessary, but that seems awkward so I don't really like that idea. Please let me know if you think of a good way to do this.

Thanks,
Benbuck

**Comment by bnason-nf** [comment]
Hi @SAbboushi,

It looks like this issue is requesting something like what you want:

https://github.com/microsoft/vscode/issues/23633

I will keep an eye on that issue in case there's any progress, but for now I'm going to close this since there doesn't seem to be a good way to implement it. Please let me know if you have any new information that might be relevant.

Thanks,
Benbuck

**Comment by SAbboushi** [comment]
k thanks - great extension!

**Comment by bnason-nf** [comment]
Hi @SAbboushi,

The latest version of the extension now supports search history. Please give it a try and let me know if you find any problems.

Benbuck

**Comment by SAbboushi** [comment]
Great!  Any idea why extension isn't alerting me to a new version in vscode Extensions pane?

**Comment by bnason-nf** [comment]
Hi @SAbboushi,

I don't know, but first I'd recommend restarting VSCode to see if that changes anything. I know that the update has worked for some people, so if that still doesn't work maybe you could provide some more information about your local environment, version numbers, and so on?

Thanks,
Benbuck

**Comment by SAbboushi** [comment]
Currently running v. 1.0.0 of your extension.  vscode doesn't note that there is a new version whereas it does for e.g. "Gremlins..." extension:
![image](https://user-images.githubusercontent.com/1964198/109038526-6f070a80-7691-11eb-85de-15f1a3d9ba5b.png)

Search Marketplace from within vscode only shows v. 1.0.0 of your extension, which I suspect is why vscode is not notified of the newer version:

![image](https://user-images.githubusercontent.com/1964198/109038122-0750bf80-7691-11eb-96bf-5e67a8b34308.png)

"Install another version" within vscode to v. 0.9.3: again, it seems the Marketplace believes v. 1.0.0 is the most recent version:
![image](https://user-images.githubusercontent.com/1964198/109039449-6bc04e80-7692-11eb-8cea-e8ba6c68485f.png)

Looks like I'll need to download your new version directly from Git

**Comment by SAbboushi** [comment]
K my bad: I wasn't running latest version of vscode which realized your extension wasn't compatible.  Updating now -- looking forward to trying the new version -- thanks!

**Comment by bnason-nf** [comment]
Hi @SAbboushi,

Thanks for letting me know, I was struggling to think of potential explanations, and that hadn't occurred to me. I think in order to publish a new version of any extension, it has to be authored against the latest VSCode version, so I don't think I could avoid this issue, but at least I'll know the reason now if anyone else runs into this problem.

Benbuck

**Comment by SAbboushi** [comment]
Works great!
